# Generated by Django 4.2.7 on 2023-12-04 01:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tiendaApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='CompraProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.PositiveIntegerField(verbose_name='Número de Factura')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('rut_proveedor', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT del proveedor')),
                ('correo_proveedor', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico del proveedor')),
                ('fecha_compra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/fotos_perfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del Tipo')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=50, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otros')], default='m', max_length=1)),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('correo', models.CharField(max_length=50, verbose_name='E-Mail')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('foto', models.ImageField(default='usuarios/usuario.png', null=True, upload_to=tiendaApp.models.Usuario.generarNombre)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tiendaApp.tipo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['nombre', 'paterno', 'materno'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=100)),
                ('materno', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_trabajadores')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaApp.perfiltrabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la subcategoría')),
                ('creado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendaApp.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'db_table': 'subcategoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca del producto')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio del producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Stock del producto')),
                ('primerJuguete', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción del producto')),
                ('creado', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(default='productos/producto.png', null=True, upload_to=tiendaApp.models.Producto.generarNombre)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendaApp.categoria')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendaApp.subcategoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.IntegerField(verbose_name='Precio Unitario')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tiendaApp.compraproveedor')),
            ],
        ),
    ]
