# Generated by Django 4.2.7 on 2023-11-13 20:38

from django.db import migrations, models
import django.db.models.deletion
import tiendaApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la subcategoría')),
                ('creado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendaApp.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'db_table': 'subcategoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('cantidad', models.IntegerField(verbose_name='Stock del producto')),
                ('primerJuguete', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción del producto')),
                ('creado', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(default='productos/producto.png', null=True, upload_to=tiendaApp.models.Producto.generarNombre)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendaApp.categoria')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendaApp.subcategoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
