# Generated by Django 4.1 on 2023-12-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfiltrabajador',
            options={'verbose_name': 'perfil trabajador', 'verbose_name_plural': 'perfil trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'trabajador', 'verbose_name_plural': 'trabajadores'},
        ),
        migrations.AlterModelTable(
            name='perfiltrabajador',
            table='perfil trabajador',
        ),
        migrations.AlterModelTable(
            name='trabajador',
            table='trabajador',
        ),
    ]
