# Generated by Django 4.2.7 on 2023-12-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.IntegerField(verbose_name='Precio Unitario'),
        ),
    ]
