# Generated by Django 4.2.7 on 2023-12-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_alter_detallecompra_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=1111111111, max_length=15, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
