# Generated by Django 4.2.7 on 2023-11-26 21:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tiendaApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_mensajecontacto_perfiltrabajador_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del Tipo')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=50, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otros')], default='m', max_length=1)),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('correo', models.CharField(max_length=50, verbose_name='E-Mail')),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('foto', models.ImageField(default='usuarios/usuario.png', null=True, upload_to=tiendaApp.models.Usuario.generarNombre)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tiendaApp.tipo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['nombre', 'paterno', 'materno'],
            },
        ),
    ]
