# Generated by Django 4.2.7 on 2023-12-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Stock del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio del producto'),
        ),
    ]
