# Generated by Django 4.2.7 on 2023-12-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraproveedor',
            name='fecha_compra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='total',
            field=models.IntegerField(verbose_name='Total'),
        ),
    ]
