# Generated by Django 4.2.7 on 2023-11-26 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='contraseña',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
