# Generated by Django 4.2.7 on 2023-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0004_alter_compraproveedor_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraproveedor',
            name='numero_factura',
            field=models.PositiveIntegerField(max_length=50, verbose_name='Número de Factura'),
        ),
    ]
