# Generated by Django 4.2.7 on 2023-11-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0004_alter_trabajador_contraseña_alter_trabajador_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
