# Generated by Django 4.2.7 on 2023-11-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_alter_trabajador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
