# Generated by Django 4.2.7 on 2023-12-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_alter_compraproveedor_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraproveedor',
            name='numero_factura',
            field=models.PositiveIntegerField(verbose_name='Número de Factura'),
        ),
    ]
