# Generated by Django 4.1 on 2023-11-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='quantity',
            new_name='cantidad',
        ),
    ]
